# Generated by Django 4.2.1 on 2023-05-10 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0002_alter_sales_postal_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
