# Generated by Django 4.2.1 on 2023-05-10 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0005_alter_sales_sales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
